<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="8668568.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vionet\Vionet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="8668568.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NeuralNetworks\model_config_EMNIST.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NeuralNetworks\model_config_printedCyrrilic.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NeuralNetworks\model_config_printedEnglish.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
